version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./instance:/app/instance
    environment:
      - SECRET_KEY=your_secret_key_here
    restart: unless-stopped
